services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pfa_db
      POSTGRES_USER: pfa_user
      POSTGRES_PASSWORD: pfa_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: